#!/usr/bin/env node

import { Command } from "commander";
import * as fs from "fs";
import * as path from "path";
import chalk from "chalk";

const program = new Command();

program
    .name("timeslot")
    .description("CLI tool for @myorg/timeslot-manager initialization")
    .version("1.0.0");

program
    .command("init")
    .description("Initialize TimeSlot schema in your Prisma project")
    .option(
        "-p, --prisma-path <path>",
        "Path to your prisma directory",
        "./prisma"
    )
    .action((options) => {
        try {
            const prismaDir = path.resolve(process.cwd(), options.prismaPath);
            const schemaPath = path.join(prismaDir, "schema.prisma");

            console.log(chalk.blue("🚀 Initializing TimeSlot Manager..."));

            if (!fs.existsSync(prismaDir)) {
                console.log(
                    chalk.red(`❌ Prisma directory not found at: ${prismaDir}`)
                );
                console.log(
                    chalk.yellow('💡 Please run "npx prisma init" first')
                );
                process.exit(1);
            }

            const timeSlotSchema = `
// TimeSlot Manager Schema
// Generated by @myorg/timeslot-manager

model TimeSlot {
  id         String   @id @default(uuid())
  type       String   // WEEKLY, FLEXIBLE, DAY_ONLY
  dayOfWeek  Int?     // 0-6 for WEEKLY slots
  date       String?  // YYYY-MM-DD for FLEXIBLE and DAY_ONLY
  startTime  String?  // HH:MM format
  endTime    String?  // HH:MM format
  isBooked   Boolean  @default(false)
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt

  @@index([type])
  @@index([isBooked])
  @@index([date])
  @@index([dayOfWeek])
  @@map("time_slots")
}
`;

            if (fs.existsSync(schemaPath)) {
                const existingSchema = fs.readFileSync(schemaPath, "utf-8");

                if (existingSchema.includes("model TimeSlot")) {
                    console.log(
                        chalk.yellow(
                            "⚠️  TimeSlot model already exists in your schema"
                        )
                    );
                    console.log(chalk.green("✅ No changes needed"));
                    return;
                }

                // Append to existing schema
                fs.appendFileSync(schemaPath, `\n${timeSlotSchema}`);
                console.log(
                    chalk.green("✅ TimeSlot model added to your schema")
                );
            } else {
                console.log(
                    chalk.red(`❌ schema.prisma not found at: ${schemaPath}`)
                );
                process.exit(1);
            }

            console.log(chalk.blue("\n📋 Next steps:"));
            console.log(
                chalk.white(
                    "  1. Run: npx prisma migrate dev --name add_timeslot"
                )
            );
            console.log(chalk.white("  2. Run: npx prisma generate"));
            console.log(
                chalk.white("  3. Start using TimeSlotService in your code\n")
            );

            console.log(chalk.green("🎉 Initialization complete!"));
        } catch (error) {
            console.error(chalk.red("❌ Error during initialization:"), error);
            process.exit(1);
        }
    });

program.parse();
